### PR TITLE
chore(deps): bump domain from 0.9.3 to 0.10.0

### PR DESCRIPTION
**Pull request by esensar**
Closes: https://github.com/vectordotdev/vrl/pull/828

---
>Sponsored by [Quad9](https://quad9.net/)

### CODE REVIEW

**Comment by esensar** [comment]
Replacement for #828

**Review by jszwedko — APPROVED** [review]
Thanks @esensar

**Comment by pront** [comment]
Neat, thanks!

**Comment by jszwedko** [comment]
@esensar just a note that it looks like the tests need to be updated. You can run `./scripts/vrl_tests.sh` locally to see the failure.

**Comment by esensar** [comment]
> @esensar just a note that it looks like the tests need to be updated. You can run `./scripts/vrl_tests.sh` locally to see the failure.

Yeah, it is the issue with examples that I mentioned in #828. Not sure how to resolve that, without just removing examples or `id` from header.

**Comment by esensar** [comment]
I have made a decision to remove `id` from header for now. I think it would be good to expand VRL example tests with an option to skip tests (but since `Example` is constructed directly, that would require change in all functions to add that extra skip parameter) and then we could add it back so that we can keep these examples with `id` in `dns_lookup`.

**Review by jszwedko — APPROVED** [review]
Thanks @esensar !

**Comment by jszwedko** [comment]
I agree it could be useful to have an option to skip tests. For other functions that return dynamic values, we've used simpler assertions in the examples. For example, the `uuid_v4` example: https://github.com/vectordotdev/vrl/blob/e05fee7c40ba2eac0dd8e4b9c1336c0af70a69ee/src/stdlib/uuid_v4.rs#L18-L24

**Comment by esensar** [comment]
> I agree it could be useful to have an option to skip tests. For other functions that return dynamic values, we've used simpler assertions in the examples. For example, the `uuid_v4` example: https://github.com/vectordotdev/vrl/blob/e05fee7c40ba2eac0dd8e4b9c1336c0af70a69ee/src/stdlib/uuid_v4.rs#L18-L24

Oh, didn't think about doing it like that. That makes sense, although in this case I think this solution is fine for now.

**Pull request merged**
