### PR TITLE
Added a Community ID Function to the stdlib

### PR DESCRIPTION
**Pull request by owen5mith**
This PR addresses #359 by adding a Community ID Function. This is my first time writing Rust, so sorry in advance! 😄  

One question I did have was around benchmarks. I have seen the `benches/stdlib.rs` file, should I be adding this function to those benchmarks, and if so, how do I get them to run? I've tried various `cargo bench` commands but have not managed to get any of the stdlib benchmarks to execute.

### CODE REVIEW

**Comment by pront** [comment]
Thank you @owen5mith for this PR!

I will do a detailed review shortly but to answer your question about benchmarks, can you try: 
```
cd VRL_REPO_ROOT
cargo bench
```

Adding it to `benches/stdlib.rs` would be nice but not strictly necessary for this PR.

**Review by pront — CHANGES_REQUESTED** [review]
@owen5mith: Thank you for submitting this PR!

This mostly looks good.I left some minor comments but most importantly some tests are failing. I will review again as soon as they are fixed.

**Comment by pront** [comment]
Hi @owen5mith, we are almost there. 

In order to fix some failing workflows, can you `cd` into the vector repo root and run: 
```
cargo install -f --path vdev
cargo vdev check rust --clippy
# if clippy reports any errors, please fix 
cargo vdev fmt
# this will ensure is the formatting is good
# commit all changes  
```

**Comment by owen5mith** [comment]
Hey @pront, sorry for the delay, I was waiting for this [PR](https://github.com/traceflight/rs-community-id/pull/2) to be merged, which I hope means this can now compile to WASM. This should now be ready for a re-review. I've run clippy against it, however there were no changes.

**Review by pront — APPROVED** [review]

**Comment by pront** [comment]
Hi @owen5mith, this looks good now!

**Comment by owen5mith** [comment]
> Hi @owen5mith, this looks good now! 

Thanks, let me know if I need to add anything else to get this merged! 😀

**Comment by jszwedko** [comment]
Thanks for this contribution @owen5mith !

**Pull request merged**
