### PR TITLE
Add traceability_id field to alb log parse

### PR DESCRIPTION
**Pull request by skbki**
Apparently AWS added new field to ALB log which broke our ingestion pipeline. Only place I found it is AWS Athena guide to parse ALB logs
https://docs.aws.amazon.com/athena/latest/ug/application-load-balancer-logs.html

Closes: https://github.com/vectordotdev/vrl/issues/852

### CODE REVIEW

**Comment by misterek** [comment]
This is currently breaking all of our ALB log parsing.

However, is it possible to adjust so that new fields are ignored, not breaking everything?  This is apparently being rolled out slowly region to region, so some amount of logs will be broken.

**Review by jszwedko — COMMENTED** [review]
Thanks for this contribution @skbki !

I think the `traceability_id` field needs to be optional since it appears that AWS seems to still be rolling out this change and so there may be users where this field doesn't exist yet (or if they are processing older ALB logs). Your change here makes the field required.

I agree with https://github.com/vectordotdev/vrl/pull/862#issuecomment-2142803345 that we should also be conservative and just discard unknown fields to future-proof this function, but that could be handled separately from the PR simply adding support for `traceability_id`.

**Comment by skbki** [comment]
Good point. I've managed to make the field optional

**Review by jszwedko — APPROVED** [review]
Thanks @skbki . This looks good to me!

**Review by jszwedko — COMMENTED** [review]
We'll just need a [changelog entry](https://github.com/vectordotdev/vrl/blob/ef07d02e20e021263ddfffb632c22148214d27ec/CHANGELOG.md) too.

**Comment by pront** [comment]
Hi @skbki, thank you for this contribution! A `cargo fmt` should fix the failing CI check.

**Comment by jszwedko** [comment]
Clippy flagged an issue too (`cargo clippy` should show it locally).

**Comment by skbki** [comment]
Corrected issues, should be fine now

**Pull request merged**
