### PR TITLE
Deprecate "to_timestamp" function

### PR DESCRIPTION
**Pull request by pront**
closes: #188 

- The change to [parse_nginx_access_log.vrl](https://github.com/vectordotdev/vrl/pull/285/files#diff-21cbd7764da28bcba6989340c3c970e3199f4529615702bd773c2a5fa2ef1710) is interesting, now the date format needs to be defined explicitly.

### CODE REVIEW

**Review by fuchsnj — APPROVED** [review]
Overall this looks good. Just wanted to note that we also generally check the Vector [regression tests](https://github.com/vectordotdev/vector/tree/master/regression/cases) for any usage of the deprecated function and replace those, but I don't see any so you should be good there.

**Comment by fuchsnj** [comment]
Forgot to mention: please add a changelog entry for this.

**Comment by pront** [comment]
Should we remove this https://github.com/vectordotdev/vrl/blob/main/LICENSE-3rdparty.csv#L91?

**Comment by jszwedko** [comment]
> Should we remove this https://github.com/vectordotdev/vrl/blob/main/LICENSE-3rdparty.csv#L91?

I had noticed this as well in #288 . I opened https://github.com/vectordotdev/vrl/pull/290 to update the license file.

**Pull request merged**
